credentialFactory.class=org.frankframework.credentialprovider.PropertyFileCredentialFactory
credentialFactory.map.properties=../Notificatie-Component/src/main/secrets/credentials.properties

# docker mounts the credentials file to /opt/frank/secrets/credentials.properties
#credentialFactory.map.properties=/opt/frank/secrets/credentials.properties
