warnings.suppress.sqlInjections.ManageDatabase=true
# While everything is correctly stubbed, for whatever reason Larva is not available.
stub4testtool.configuration=true

application.security.console.authentication.type=NONE
application.security.testtool.authentication.type=NONE
