@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Context diagram

System_Ext(ZGWExt, "ZGW Applicatie", "Registreert abonnementen / Verzoek aanvraag")
System_Ext(OZ, "Open Zaak", "(Een ZGW Applicatie) Publiceert events")
System_Ext(AC, "Autorisatie Component", "Valideert autorisaties")

System(NC, "Notificatie Component", "Beheert kanalen, abonnementen, verzoeken en events")

Rel(ZGWExt, NC, "Registreert abonnement", "HTTP")
Rel(OZ, NC, "Publiceert events", "HTTP")
Rel(NC, AC, "Valideert autorisatie", "HTTP")
Rel(NC, OZ, "ZGW Applicatie verzoek doorsturen", "HTTP")
Rel(NC, ZGWExt, "Notificaties versturen", "HTTP Callback")

@enduml